-- Seed Users with Legacy Points
-- Run this in Supabase SQL Editor to populate users
-- Each user gets a random emoji icon and appropriate leader status

INSERT INTO users (name, is_leader, total_points, "emojiIcon", created_at, updated_at) VALUES
  ('Alexander Grant', false, 0, '🎯', now(), now()),
  ('Anabelle', false, 0, '🌟', now(), now()),
  ('Aubriana', false, 0, '🎨', now(), now()),
  ('Aubriana Holt', false, 0, '🦋', now(), now()),
  ('Avery N', false, 0, '🌈', now(), now()),
  ('Avery Rogers', false, 0, '🎭', now(), now()),
  ('Brecken Brown', false, 0, '⚡', now(), now()),
  ('Caroline Barnett', false, 0, '🌸', now(), now()),
  ('Cayden Holt-Mitchell', false, 0, '🚀', now(), now()),
  ('Ceilya McLawhorn', false, 0, '🎪', now(), now()),
  ('Connor', false, 0, '🏀', now(), now()),
  ('Cooper S', false, 0, '⚽', now(), now()),
  ('Daniel Greenhaw', false, 0, '🎮', now(), now()),
  ('Elijah Kaplan', false, 0, '🎸', now(), now()),
  ('Emma Marsh', false, 190, '🌺', now(), now()),
  ('Erika McCracken', false, 150, '🦄', now(), now()),
  ('Evie Petterson', false, 75, '🎀', now(), now()),
  ('Gavin Carter', false, 75, '🏈', now(), now()),
  ('Hudson Griggs', false, 175, '🎯', now(), now()),
  ('Jack Elder', false, 200, '⭐', now(), now()),
  ('Jacob', false, 100, '🔥', now(), now()),
  ('Jake Aylward', false, 220, '🎲', now(), now()),
  ('James Stone', false, 70, '🌊', now(), now()),
  ('Jeremiah', false, 0, '🎵', now(), now()),
  ('Jeremiah Jackson', false, 0, '🎺', now(), now()),
  ('Jeremy Taylor', true, 0, '🎓', now(), now()),
  ('Jonah Jackson', false, 35, '🐠', now(), now()),
  ('Jonah Miller', false, 0, '🌟', now(), now()),
  ('Jordynn Tenpow', false, 100, '💫', now(), now()),
  ('Joshua Jackson', false, 0, '🏆', now(), now()),
  ('JR', true, 45, '👑', now(), now()),
  ('Judah', true, 0, '🦁', now(), now()),
  ('Kalani', false, 0, '🌴', now(), now()),
  ('Keegan White', false, 120, '⚡', now(), now()),
  ('Kennedy', false, 0, '🎀', now(), now()),
  ('Kristopher Salter', false, 100, '🎯', now(), now()),
  ('Lillyanna Grant', false, 75, '🌷', now(), now()),
  ('Lily White', false, 75, '🌼', now(), now()),
  ('Mackenzie Moore', false, 0, '🦋', now(), now()),
  ('Magnolia', false, 0, '🌺', now(), now()),
  ('Malcom', false, 300, '🚀', now(), now()),
  ('Mark Zeigler', false, 150, '🎸', now(), now()),
  ('Matias Costlow', false, 0, '⚽', now(), now()),
  ('Maya Zeigler', false, 150, '🎨', now(), now()),
  ('Meg', false, 220, '✨', now(), now()),
  ('Meridith', false, 75, '🌈', now(), now()),
  ('Michaela Costlow', false, 100, '🎭', now(), now()),
  ('mylah', false, 0, '🌸', now(), now()),
  ('Naomi Salter', false, 200, '💎', now(), now()),
  ('Nate Burkett', false, 200, '🏀', now(), now()),
  ('Norah', false, 150, '🌟', now(), now()),
  ('Norah C', false, 100, '⭐', now(), now()),
  ('Oakley Brown', false, 100, '🌳', now(), now()),
  ('Oliva', true, 0, '🎓', now(), now()),
  ('Piper', false, 100, '🎵', now(), now()),
  ('Presley McLawhorn', false, 75, '🎪', now(), now()),
  ('Rebecca Greenhaw', true, 130, '📚', now(), now()),
  ('Richie Paulin', false, 100, '🎮', now(), now()),
  ('Ryan Aylward', false, 250, '🏈', now(), now()),
  ('Sadie', false, 200, '🌺', now(), now()),
  ('Saoirse', false, 150, '🍀', now(), now()),
  ('Sawyer Mclawhorn', false, 75, '🎯', now(), now()),
  ('Sawyer Petterson', false, 80, '⚡', now(), now()),
  ('Skylar', true, 0, '🌠', now(), now()),
  ('Sloan', false, 150, '💫', now(), now()),
  ('Stephen Greenhaw', false, 0, '🔥', now(), now()),
  ('Tommy McCracken', false, 150, '🎲', now(), now()),
  ('Trinity B', false, 0, '👑', now(), now()),
  ('Weston Elder', false, 90, '🏆', now(), now()),
  ('Wyatt', false, 225, '🚀', now(), now()),
  ('Zayden Holt-Mitchell', false, 0, '⚽', now(), now()),
  ('Faye', false, 200, '🌸', now(), now()),
  ('Carson', false, 150, '🎸', now(), now()),
  ('Josephine', false, 100, '🦋', now(), now()),
  ('Meredith', false, 115, '🌈', now(), now()),
  ('Norah carter', false, 120, '🌟', now(), now()),
  ('Malachi Elder', false, 200, '🦁', now(), now()),
  ('Peter Williams', true, 0, '📖', now(), now()),
  ('Josie', false, 80, '💐', now(), now()),
  ('Lucy', false, 0, '🌷', now(), now()),
  ('Ezekiel Brown', false, 100, '🔥', now(), now()),
  ('Karina', false, 100, '💎', now(), now()),
  ('Montez', false, 100, '⭐', now(), now()),
  ('Kelsie', false, 0, '🎀', now(), now()),
  ('Brett', true, 0, '🎓', now(), now()),
  ('Bryant', true, 0, '📚', now(), now()),
  ('Hadleigh', false, 0, '🌺', now(), now()),
  ('Harper', false, 100, '🦄', now(), now()),
  ('Adeline', false, 200, '✨', now(), now()),
  ('Katalina', false, 170, '💫', now(), now()),
  ('Hunter', false, 0, '🏹', now(), now()),
  ('Peyton', false, 0, '🏀', now(), now()),
  ('Carson S.', false, 150, '🎯', now(), now()),
  ('Mackenzie', false, 0, '🎨', now(), now()),
  ('Gavin', false, 0, '⚡', now(), now());

-- Verify users were created
SELECT COUNT(*) as total_users, 
       SUM(CASE WHEN is_leader THEN 1 ELSE 0 END) as leaders,
       SUM(total_points) as total_legacy_points
FROM users;

-- Show sample of created users
SELECT name, is_leader, total_points, "emojiIcon" 
FROM users 
ORDER BY is_leader DESC, total_points DESC 
LIMIT 20;
